### ISSUE TITLE
Allow Managed Identity to access to APIC portal

### ISSUE THREAD

**Issue by justinyoo** [Azure/api-center#24]
# What are you trying to achieve?

In this [APIC video](https://youtu.be/7Z45FdCLFbA?si=Rzu2g2G1BWpJjjEz), we have to use a service principal to access to APIC portal.

<img width="1512" alt="image" src="https://github.com/Azure/api-center-preview/assets/1538528/c73e7821-d31a-4648-91f7-2291a9e9658e">

However, APIC has already the Managed Identity feature. Can we use this managed identity to access to the APIC portal, instead of creating a new service principal?

# Proposed solution

- Use Managed Identity, users can access to the APIC portal.

# Additional context

Managed Identity (MI) is basically working as like a Service Principal, which is the same as the app registered through App Registration. MI works slightly differently though.
 
To me, it gives me implication that the app registration process outside APIC blocks users from being more accessible because they have to be out of the APIC screen 👉 Go to Entra ID 👉 Do the app registration 👉 Do all the permissions stuff 👉 Be back to APIC to finalise.
 
I think the purpose of MI is to simplify these steps. Please correct me if I'm wrong about MI.

**Comment by kkgthb** [comment]
@justinyoo , I don't work for Microsoft, so I might be wrong, but I believe that the reason you need to create an [Entra App Registration _("AppReg")_](https://katiekodes.com/entra-app-registration/) is because:

Any website that gives humans an opportunity to click a "sign in" button and then sign into that website as their human Entra identity...
...needs to be able to tell those humans _**what**_ website it is that's asking for them to click a "yes, go ahead and log in as my Entra identity; I trust this website to know who I am" prompt.

Typing the "What website I am" information in is something that can only be stored on an AppReg, not on the [Entra/Azure System-Assigned Managed Identity _("SMI")_](https://katiekodes.com/entra-azure-system-assigned-managed-identity/) that you can flip on for a given Azure APIC resource.

So, while things like your APIC resource's SMI's associated Entra Service Principal can do things like serve as the principal for an [Azure RBAC Role Assignment](https://katiekodes.com/azure-rbac-role-assignment/) _(e.g. so that your APIM resource can let your APIC resource in as a reader of what all is sitting around in APIM)_...

...I believe that saying "Hi, I'm website X -- are you sure you want to log into me as your Entra human identity?" isn't something that can be done through an Entra Service Principal at all.

Therefore, it's not actually the Entra Service Principal associated with an AppReg that you're interested in when you create the AppReg, in this case.  Which is why a SMI isn't an alternative to an AppReg.

Instead, I believe what you're creating the AppReg for is its ability to say, "Hi, I'm website X!"

**Comment by pierceboggan** [comment]
@kkgthb is spot on here! We still need to do an app registration for the reasons explained in that reply. I'll go ahead and close this - if there's any more confusion happy to chat at piboggan@microsoft.com. Thanks again for your bug report :)
